spring:
  datasource:
    #    url: jdbc:oracle:thin:@localhost:1521/xe
    #    username: gestion
    #    password: gestion
    #    url: jdbc:oracle:thin:@localhost:1521:orcl
    url: jdbc:oracle:thin:@localhost:1521/ORCL
    username: yalerolev1
    password: yalerolev1
    #    username: gestion
    #    password: gestion

    driver-class-name: oracle.jdbc.driver.OracleDriver
  application:
    name: ClientesBackend

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect

server:
  port: 8082
  servlet:
    context-path: /clientes-backend
